/************
 * Header of the parent class of Block Decoders. Do not edit this file.
 *
 * Created 9/21/2014 by Cory D. Boatright for use in COMP 342 at Grove City College
 ************/

#pragma once

#include <list>

class BlockDecoder
{
public:
	BlockDecoder(void);
	virtual ~BlockDecoder(void);

	virtual std::list<bool> decode(const std::list<bool>&) = 0;
};

