/************
 * Header for the parent class of Block Encoders.  Do not edit this file.
 *
 * Created 9/21/2014 by Cory D. Boatright for use in COMP 342 at Grove City College
 ************/

#pragma once

#include <forward_list>
#include <list>

class BlockEncoder {
public:
	BlockEncoder(void);
	virtual ~BlockEncoder(void);

	virtual std::list<bool> encode(const std::forward_list<bool>&) = 0;
};

