/************
 * Parent class for line encoders.  Do not edit this file.
 *
 * Created 9/21/2014 by Cory D. Boatright for use in COMP 342 at Grove City College
 ************/

#pragma once

#include <list>

class LineEncoder {
public:
	LineEncoder(void);
	virtual ~LineEncoder(void);

	virtual std::list<float> encode(const std::list<bool>&) = 0;

protected:
	float amplitude;
};

